keys:
  - &desktop age1c9uturjx2ehtk9x7a4yec5z3r3xpyj670lewkfqcg0vktn5kefwsakplu8
  - &kaiju age1y7gnxlsx2tq5wecl6ahenrd6rcmvx3rtq7vks0utu9vgy450ffpq9mcvx7
creation_rules:
  - key_groups:
    - age:
      - *desktop
      - *kaiju
