keys:
  - &desktop age1gjcz224g0sfx5cerygqc678kmqw67svguuyq36rczpg97ac3td8s4e88lu
creation_rules:
  - path_regex: hosts/desktop/secrets/.*\.yaml$
    key_groups:
      - age:
          - *desktop
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *desktop
  - path_regex: k8s/secrets/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - *desktop
