keys:
  - &desktop age1gjcz224g0sfx5cerygqc678kmqw67svguuyq36rczpg97ac3td8s4e88lu
  - &kaiju age1hcz0d0mq0jw6d5mmz6a0q7slwkfer6ry253y6yrc26fhjksees9q4lyplf
  - &kraken age1rwxn243045x99qu8x5j4556pmn7c50hp9xf9hsulhujmr9z36sns6nltvx
  - &glados age1vhszt0du96c22mf634n6hss96vva9qlym8dszt8telasr3vaj5hse6sxsa
  - &colossus age14m7xchp0kpegq0l0pvmd5devwgzkluynq3ymspgem7lj2fnqt36q89ujta
  - &meerkat age1zqppr46wmqr3tsjrxd9psjhts5qdrpnqe3fyeknxk5a3uudsaucsnqc9wy
creation_rules:
  - path_regex: hosts/desktop/secrets\.yaml$
    key_groups:
      - age:
          - *desktop
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *desktop
          - *kaiju
          - *kraken
          - *glados
          - *colossus
          - *meerkat
  - path_regex: k8s/secrets/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - *desktop
